Repository FRONT-END-BOOTCAMP-PLUS-4/prolog, pull requests merged in 2025-06, with the labels that each got.

#76 Feat: 카드 리스트 페이지네이션 및 필터링 시스템 구현
  app/api/posts/route.ts
  back/posts/application/dto/GetPostListAllDto.ts
  back/posts/application/dto/GetPostListAllResponseDto.ts
  back/posts/application/usecases/GetPostListAllUsecase.ts
  back/posts/domain/PostListAllRepository.ts
  back/posts/infra/PrPostListAllRepository.ts
  features/search-input/container/PostsSearchCont.tsx
  features/tag-list/container/TagListCont.tsx
  features/tag-list/presentational/TagListPres.tsx
  shared/hooks/useInfiniteScroll.ts
  shared/types/index.ts
  shared/utils/validators/index.ts
  views/home/card-list/container/CardListCont.tsx
  views/home/card-list/hooks/useInfiniteScrollTrigger.ts
  views/home/card-list/hooks/useMinSkeleton.ts
  views/home/card-list/hooks/useResetOnFilterChange.ts
  views/home/card-list/presentational/CardListPres.tsx
  widgets/card/presentational/LongCardPres.tsx
  widgets/card/presentational/SquareCardPres.tsx
  widgets/card/styles/LongCardPres.module.scss
Labels: 🐛 FIX, ✨ FEAT, ♻️ REFACTOR

#67 Refactor: 회원 및 비회원 접근 가능 코드변경 및 endPoint경로 변경
  app/api/[email]/stories/route.ts
  app/api/member/route.ts
  app/api/member/subscription/route.ts
  back/story/profile/application/usecase/GetProfileUsecase.ts
  back/story/profile/domain/ProfileRepository.ts
  back/story/profile/infra/PrProfileRepository.ts
  features/subscription/container/SubscriptionCont.tsx
  views/story/profile-card/container/ProfileCardCont.tsx
Labels: ♻️ REFACTOR

#78 Feat : AI 목차 요약 기능 작업
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/ai/route.ts
  app/api/ai/summarize/route.ts
  app/generated/prisma/edge.js
  app/generated/prisma/index-browser.js
  app/generated/prisma/index.d.ts
  app/generated/prisma/index.js
  app/generated/prisma/package.json
  app/generated/prisma/schema.prisma
  app/generated/prisma/wasm.js
  back/ai/application/usecases/CreateAiSummary.ts
  back/ai/domain/AiRepository.ts
  back/ai/domain/entities/AiSummary.ts
  back/ai/infra/OpenAiRepository.ts
  back/posts/application/dto/CreatePostDto.ts
  back/posts/application/dto/GetPostViewDto.ts
  back/posts/infra/PrPostsRepository.ts
  package-lock.json
  package.json
  prisma/migrations/20250601134548_change_ai_summary_to_array/migration.sql
  prisma/migrations/20250601141051_change_ai_summary_to_json/migration.sql
  prisma/schema.prisma
  views/detail/post-detail/container/AiSummaryCont.tsx
  views/detail/post-detail/presentational/AiSummaryPres.tsx
  views/detail/post-detail/styles/AiSummaryPres.module.scss
  views/post/post-draft/types.ts
  views/post/post-form/container/PostAiSummaryCont.tsx
  views/post/post-form/container/PostFormCont.tsx
  views/post/post-form/presentational/PostAiSummaryPres.tsx
  views/post/post-form/presentational/PostFormPres.tsx
  views/post/post-form/styles/PostAiFormPres.module.scss
  views/post/post-form/styles/PostFormPres.module.scss
Labels: 🐛 FIX, ✨ FEAT, ⚙️ CHORE, ♻️ REFACTOR, 💬 COMMENT

#83 Style: 모바일 화면에서 게시글 수정 버튼 숨김 처리
  app/(user)/[email]/stories/[id]/page.tsx
  app/(user)/[email]/stories/[id]/styles.module.scss
Labels: 🎨 STYLE

#77 Refactor: 홈 화면 전체 스타일 리뉴얼 및 기능 점검
  app/header/presentational/HeaderPres.tsx
  back/posts/domain/PostListAllRepository.ts
  back/posts/infra/PrPostListAllRepository.ts
  features/search-input/container/PostsSearchCont.tsx
  features/search-input/styles/SearchInputPres.module.scss
  features/select/container/SelectCont.tsx
  features/select/index.ts
  features/select/types.ts
  shared/hooks/useInfiniteScroll.ts
  shared/hooks/useLocalStorage.ts
  shared/hooks/useOnClickOutside.ts
  shared/types/index.ts
  shared/ui/profile/Profile.module.scss
  shared/ui/tag/Tag.module.scss
  views/home/card-list/container/CardListCont.tsx
  views/home/card-list/presentational/CardListPres.tsx
  widgets/card/presentational/LongCardPres.tsx
  widgets/card/presentational/SquareCardPres.tsx
  widgets/card/styles/LongCardPres.module.scss
Labels: 🐛 FIX, ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#84 Refactor: 클라이언트 백엔드 프로필정보 데이터바인딩 수정
  app/(user)/[email]/stories/page.tsx
  app/api/[email]/stories/route.ts
  app/header/container/CheckUserCont.tsx
  app/header/presentational/HeaderPres.tsx
  back/story/profile/application/usecase/GetProfileUsecase.ts
  back/story/profile/domain/ProfileRepository.ts
  back/story/profile/infra/PrProfileRepository.ts
  views/story/profile-card/container/ProfileCardCont.tsx
  widgets/card/presentational/LongCardPres.tsx
  widgets/card/presentational/SquareCardPres.tsx
Labels: ♻️ REFACTOR

#85 Feat : 게시글 수정 기능 구현 및 API 연동 작업
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/member/posts/[id]/route.ts
  app/member/story/edit/[id]/page.tsx
  features/edit/container/EditButtonCont.tsx
  features/edit/types.ts
  views/post/post-draft/types.ts
  views/post/post-form/container/PostFormCont.tsx
Labels: ✨ FEAT

#87 Feat: 댓글 작성&조회 백엔드 작업
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/member/comments/route.ts
  app/api/posts/[id]/route.ts
  back/comments/application/dto/CreateCommentDto.ts
  back/comments/application/dto/GetCommentDto.ts
  back/comments/application/usecases/CreateCommentUsecase.ts
  back/comments/application/usecases/GetCommentListUsecase.ts
  back/comments/domain/CommentRepository.ts
  back/comments/infra/PrCommentRepository.ts
  back/posts/application/usecases/GetPostUsecase.ts
  back/posts/domain/PostsRepository.ts
  back/posts/infra/PrPostsRepository.ts
  views/detail/post-detail/container/CommentInputCont.tsx
  views/detail/post-detail/container/CommentListCont.tsx
  views/detail/post-detail/presentational/CommentListPres.tsx
Labels: ✨ FEAT

#74 refactor/notification: 구조변경
  app/api/member/notifications/route.ts
  app/login-ssr/page.tsx
  back/alarm/application/dto/GetAlarmListDto.ts
  back/alarm/application/usecases/GetAlarmListUsecase.ts
  back/alarm/domain/AlarmRepository.ts
  back/alarm/infra/PrAlarmRepository.ts
  features/delete/container/DeleteButtonCont.tsx
  features/delete/presentational/DeleteButtonPres.tsx
  features/delete/styles/DeleteButtonPres.module.scss
  features/notification-delete/container/DeleteNotificationCont.tsx
  features/notification-delete/container/NotificationDeleteCont.tsx
  features/notification-delete/index.ts
  features/notification-list/container/NotificationListCont.tsx
  features/notification-list/index.ts
  features/notification-list/presentational/NotificationListPres.tsx
  features/notification-list/styles/NotificationListPres.module.scss
  features/notification-list/types.ts
  features/notification-mark-all-read/container/MarkAllReadCont.tsx
  features/notification-mark-all-read/index.ts
  features/notification-read/container/NotificationReadCont.tsx
  features/notification-read/index.ts
  widgets/notification/container/NotificationModalCont.tsx
  widgets/notification/presentational/NotificationModalPres.tsx
  widgets/notification/styles/NotificationModalPres.module.scss
Labels: ✨ FEAT, ♻️ REFACTOR

#89 Revert: 파일복구
  features/delete/container/DeleteButtonCont.tsx
  features/delete/presentational/DeleteButtonPres.tsx
  features/delete/styles/DeleteButtonPres.module.scss
Labels: ⚙️ CHORE, ⛔️ REMOVE

#91 Feat: auth user
  app/(auth)/auth.ts
  app/generated/prisma/edge.js
  app/generated/prisma/index.d.ts
  app/generated/prisma/index.js
  app/generated/prisma/package.json
  app/generated/prisma/schema.prisma
  prisma/migrations/20250602023601_emailandname/migration.sql
  prisma/schema.prisma
  tsconfig.json
Labels: ✨ FEAT

#92 Feat : markdown 을 html 로 변환해주는 작업 및 상세페이지 스타일 개선
  app/(user)/[email]/stories/[id]/page.tsx
  biome.json
  package-lock.json
  package.json
  views/detail/post-detail/presentational/BodyTextPres.tsx
  views/detail/post-detail/styles/BodyTextPres.module.scss
Labels: ✨ FEAT, ⚙️ CHORE

#95 Refactor: 카드 필터링 방식 변경
  app/header/presentational/HeaderPres.tsx
  app/styles/_reset.scss
  back/posts/application/dto/GetPostListAllResponseDto.ts
  back/posts/application/usecases/GetPostListAllUsecase.ts
  features/tag-list/styles/TagList.module.scss
  shared/types/index.ts
  views/home/card-list/container/CardListCont.tsx
  views/home/card-list/presentational/CardListPres.tsx
Labels: 🐛 FIX, ✨ FEAT, ♻️ REFACTOR

#97 fix: myblog(stories) build 경로 오류 수정
  app/api/member/subscription/follower/route.ts
  app/api/member/subscription/following/route.ts
  app/api/member/subscription/route.ts
  back/subscribe/infra/PrSubscribeRepository.ts
Labels: ✍🏻 RENAME

#104 Feat: 댓글 수정&삭제 백엔드 작업
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/comments/count/route.ts
  app/api/comments/route.ts
  app/api/member/comments/[id]/route.ts
  app/api/member/comments/route.ts
  back/comments/application/dto/GetCommentDto.ts
  back/comments/application/dto/UpdateCommentDto.ts
  back/comments/application/usecases/DeleteCommentUsecase.ts
  back/comments/application/usecases/GetCommentCountUsecase.ts
  back/comments/application/usecases/GetCommentListUsecase.ts
  back/comments/application/usecases/UpdateCommentUsecase.ts
  back/comments/domain/CommentRepository.ts
  back/comments/infra/PrCommentRepository.ts
  features/delete/container/DeleteButtonCont.tsx
  views/detail/post-detail/container/CommentCountCont.tsx
  views/detail/post-detail/container/CommentInputCont.tsx
  views/detail/post-detail/container/CommentListCont.tsx
  views/detail/post-detail/index.ts
  views/detail/post-detail/presentational/CommentCountPres.tsx
  views/detail/post-detail/presentational/CommentListPres.tsx
  views/detail/post-detail/stores/useCommentStore.ts
  views/detail/post-detail/styles/CommentListPres.module.scss
  views/detail/post-detail/types.ts
Labels: ✨ FEAT

#106 Fix: 게시글 상세 조회 및 인증/임시저장 관련 로직 수정
  app/api/member/posts/drafts/route.ts
  app/api/member/posts/route.ts
  back/posts/application/dto/GetPostViewDto.ts
  back/posts/application/usecases/GetPostUsecase.ts
  back/posts/infra/PrPostsRepository.ts
  features/edit/container/EditButtonCont.tsx
  features/edit/types.ts
  views/post/post-form/container/PostFormCont.tsx
  views/post/post-form/presentational/PostAiSummaryPres.tsx
Labels: 🐛 FIX, 💬 COMMENT

#108 Fix : 댓글 삭제 API에서 params를 Promise 형태로 처리하도록 수정
  app/api/member/comments/[id]/route.ts
Labels: 🐛 FIX

#109 Fix: 댓글 수정 API 에서 params 를 Promise 로 수정
  app/api/member/comments/[id]/route.ts
Labels: 🐛 FIX

#112 Fix: getToken 함수를 auth 로 모두 수정
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/comments/route.ts
  app/api/member/comments/[id]/route.ts
  app/api/member/comments/route.ts
  app/api/member/notifications/route.ts
  app/api/member/posts/drafts/route.ts
  app/api/posts/[id]/route.ts
Labels: 🐛 FIX

#110 Feat: 게시글 삭제 백엔드 작업
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/member/posts/[id]/route.ts
  back/posts/application/dto/GetPostViewDto.ts
  back/posts/application/usecases/DeletePostUsecase.ts
  back/posts/application/usecases/GetPostUsecase.ts
  back/posts/domain/PostsRepository.ts
  back/posts/infra/PrPostsRepository.ts
  features/delete/container/DeleteButtonCont.tsx
Labels: ✨ FEAT

#105 Feat: 좋아요 버튼 토글 기능 구현 및 API 연동
  app/api/member/likes/route.ts
  app/api/posts/route.ts
  back/like/application/dto/ToggleLikeDto.ts
  back/like/application/usecase/ToggleLikeUsecase.ts
  back/like/domain/ToggleLikeRepository.ts
  back/like/infra/PrToggleLikeRepository.ts
  back/posts/application/usecases/GetPostListAllUsecase.ts
  features/like/container/LikeButtonCont.tsx
  features/like/presentational/LikeButtonPres.tsx
  shared/types/index.ts
  views/home/card-list/container/CardListCont.tsx
  views/home/card-list/hooks/useInfiniteScroll.ts
  views/home/card-list/presentational/CardListPres.tsx
  views/home/card-list/types.ts
  widgets/card/presentational/LongCardPres.tsx
  widgets/card/presentational/SquareCardPres.tsx
Labels: ✨ FEAT, ♻️ REFACTOR

#113 fix: session 유저이름 재할당
  app/(auth)/auth.ts
Labels: 🐛 FIX

#114 Fix : env 파일명 수정
  app/(user)/[email]/stories/[id]/page.tsx
Labels: 🐛 FIX

#115 fix: auth userSeesion 재설정
  app/(auth)/auth.ts
Labels: 🐛 FIX, ♻️ REFACTOR

#118 fix: 마이블로그 빌드 타입오류 해결
  views/story/myblog-card-list/container/MyBlogCardListCont.tsx
  views/story/myblog-card-list/presentational/MyBlogCardListPres.tsx
  widgets/card/presentational/LongCardPres.tsx
Labels: 🐛 FIX

#120 Feat: notFound 페이지 생성
  app/not-found.tsx
  app/styles/NotFound.module.scss
  public/images/notFound.png
  public/images/notFoundDk.png
Labels: ✨ FEAT

#122 Refactor: 카드 리스트 조회 인증 방식 변경
  app/api/posts/route.ts
Labels: ♻️ REFACTOR

#123 Feat: 북마크 백엔드 구현
  app/(user)/[email]/stories/[id]/page.tsx
  app/api/member/bookmarks/route.ts
  back/bookmark/application/dto/BookmarkDto.ts
  back/bookmark/application/usecase/BookmarkUsecase.ts
  back/bookmark/domain/BookmarkRepository.ts
  back/bookmark/infra/PrBookmarkRepository.ts
  features/bookmark/container/BookmarkButtonCont.tsx
Labels: ✨ FEAT

#124 fix: process env변경
  app/(auth)/auth.ts
  app/(user)/[email]/stories/[id]/page.tsx
Labels: 🐛 FIX, ⚙️ CHORE

#126 Feat: 댓글 삭제 시 댓글 개수 refetch
  views/detail/post-detail/container/CommentCountCont.tsx
  views/detail/post-detail/container/CommentListCont.tsx
Labels: ✨ FEAT

#125 Feat: 로딩 UI 컴포넌트(spinner, loadingbar) 생성
  app/loading.tsx
  app/not-found.tsx
  app/styles/NotFound.module.scss
  shared/ui/loading/LoadingBar.module.scss
  shared/ui/loading/index.tsx
  shared/ui/spinner/Spinner.module.scss
  shared/ui/spinner/index.tsx
Labels: ✨ FEAT

#131 Feat: 비로그인 시 댓글 로그인 버튼에 로그인 모달 연결
  views/detail/post-detail/presentational/CommentLoginPromptPres.tsx
Labels: ✨ FEAT

#129 Feat: 사용자 프로필 설정 기능 구현 및 API 연동
  app/api/member/settings/images/background/route.ts
  app/api/member/settings/images/profile/route.ts
  app/api/member/settings/images/route.ts
  app/api/member/settings/route.ts
  app/member/setting/Setting.module.scss
  app/member/setting/page.tsx
  back/setting/application/dto/SettingDto.ts
  back/setting/application/usecase/SettingUsecase.ts
  back/setting/domain/SettingRepository.ts
  back/setting/infra/PrSettingRepository.ts
  back/setting/infra/_factory.ts
  views/setting/.gitkeep
  views/setting/container/SettingCont.tsx
  views/setting/hooks/useSettingProfile.ts
  views/setting/index.ts
  views/setting/presentational/SettingPres.tsx
  views/setting/styles/Setting.module.scss
  views/setting/types.ts
  views/setting/utils/SettingApi.ts
  views/setting/utils/validateNickname.ts
Labels: ✨ FEAT

#128 Feat: posts 북마크 불러오기 구현
  app/api/story/posts/route.ts
  back/story/posts/application/dto/GetPostByUserResponseDto.ts
  back/story/posts/application/usecase/GetPostByUserUsecase.ts
  back/story/posts/domain/PostByUserRepository.ts
  back/story/posts/infra/PrPostByUserRepository.ts
  shared/utils/validators/index.ts
  views/home/card-list/types.ts
  views/story/myblog-card-list/container/MyBlogCardListCont.tsx
  views/story/myblog-card-list/hooks/useMyStoryInfiniteScroll.ts
  views/story/myblog-card-list/presentational/MyBlogCardListPres.tsx
Labels: ✨ FEAT, 💬 COMMENT

#132 Fix: 빌드 타입 오류 해결
  app/api/story/posts/route.ts
  shared/utils/validators/index.ts
Labels: 🐛 FIX

#133 Refactor: validator edit
  shared/utils/validators/index.ts
Labels: ♻️ REFACTOR

#134 Feat: 게시글 상세보기에 팔로우 기능 연결
  app/(user)/[email]/stories/[id]/page.tsx
  back/posts/application/dto/GetPostViewDto.ts
  back/posts/application/usecases/GetPostUsecase.ts
  back/posts/infra/PrPostsRepository.ts
  views/detail/post-detail/container/CommentListCont.tsx
  views/detail/post-detail/presentational/CommentListPres.tsx
  views/detail/post-detail/types.ts
Labels: ✨ FEAT

#143 Fix/editor bug
  app/header/container/CheckUserCont.tsx
  app/header/presentational/HeaderPres.tsx
  views/detail/post-detail/styles/BodyTextPres.module.scss
  views/post/post-form/styles/PostFormPres.module.scss
Labels: 🐛 FIX

#144 Refactor: handleSave username변경
  views/setting/hooks/useSettingProfile.ts
Labels: ♻️ REFACTOR

#145 Feat:auth session
  app/(auth)/auth.ts
  views/setting/hooks/useSettingProfile.ts
  views/setting/presentational/SettingPres.tsx
Labels: ⚙️ CHORE, ♻️ REFACTOR

#147 Feat: 검색 시 홈 이동 로직 커스텀 훅 분리
  app/header/presentational/HeaderPres.tsx
  features/search-input/container/PostsSearchCont.tsx
  features/search-input/hooks/useNavigateToHomeWithParams.ts
  features/search-input/index.ts
Labels: ✨ FEAT

#148 Refactor: 게시글 상세 페이지 디테일 작업
  features/delete/styles/DeleteButtonPres.module.scss
  features/edit/styles/EditButtonPres.module.scss
  features/subscription/presentational/SubscriptionPres.tsx
  views/detail/post-detail/container/CommentListCont.tsx
  views/detail/post-detail/presentational/AiSummaryPres.tsx
  views/detail/post-detail/presentational/CommentInputPres.tsx
  views/detail/post-detail/presentational/CommentListPres.tsx
  views/detail/post-detail/styles/CommentListPres.module.scss
Labels: ♻️ REFACTOR

#149 Fix : 게시글 수정 후 새글 작성 시 이전 데이터 초기화 문제 해결 및 마크다운 코드 하이라이팅 적용
  app/(auth)/auth.ts
  app/header/container/CheckUserCont.tsx
  app/header/presentational/HeaderPres.tsx
  package-lock.json
  package.json
  views/detail/post-detail/presentational/BodyTextPres.tsx
  views/detail/post-detail/styles/BodyTextPres.module.scss
  views/post/post-form/presentational/PostFormPres.tsx
  views/post/stores/usePostEditorStore.ts
  views/setting/hooks/useSettingProfile.ts
Labels: 🐛 FIX, ⚙️ CHORE

#152 Chore: stories style UI 조정
  app/(user)/[email]/stories/page.tsx
  app/(user)/[email]/stories/styles.module.scss
  features/subscription-list/styles/subscriptionList.module.scss
  views/story/myblog-card-list/container/MyBlogCardListCont.tsx
  views/story/myblog-card-list/styles/myBlogCardList.module.scss
Labels: ♻️ REFACTOR, 🎨 STYLE, 💬 COMMENT

#153 Fix: header 프로필 사진 안보이는 문제 해결 및 불필요한 콘솔 제거
  app/(auth)/auth.ts
  app/api/story/posts/route.ts
  views/detail/post-detail/container/CommentListCont.tsx
  views/post/post-form/presentational/PostAiSummaryPres.tsx
  views/post/post-form/presentational/PostFormPres.tsx
  widgets/notification/container/NotificationModalCont.tsx
Labels: 🐛 FIX

#154 Refactor: 팔로워/팔로잉 버튼 클릭 시 모달에서 올바른 리스트가 표시되도록 수정
  features/subscription-list/container/SubscriptionListCont.tsx
  views/story/profile-card/presentational/ProfileCardPres.tsx
Labels: ♻️ REFACTOR

#155 Style: 팔로우/팔로잉 리스트 모달 스타일 수정
  features/subscription-list/styles/subscriptionList.module.scss
Labels: 🎨 STYLE

#156 Refactor: 팔로워|팔로잉 모달 탭 전환 방식을 토글에서 버튼 클릭으로 변경
  features/subscription-list/container/SubscriptionListCont.tsx
  features/subscription-list/presentational/SubscriptionListPres.tsx
  features/subscription-list/styles/subscriptionList.module.scss
Labels: 🐛 FIX, ♻️ REFACTOR, 🎨 STYLE
